name: CICD

on:
  push:
    branches: ["master"]

env:
  docker_image: luandnh1998/svelte-my-resume

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache: true

      - name: Install Package
        run: bun install

      - name: Build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          bun run build
          cp package.json build
          cp bun.lockb build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: publish_dev_ui
          keep_files: false

      - name: Build
        run: |
          ls -lah
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.docker_image }}:latest
